# Generated by Django 5.0.6 on 2024-05-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('photo', models.FileField(upload_to='%Y/%m/%d/', verbose_name='Медиа')),
            ],
        ),
        migrations.CreateModel(
            name='Kilometers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=4, verbose_name='Километр')),
                ('distance', models.IntegerField(max_length=4, verbose_name='Протяженность')),
                ('start', models.DecimalField(decimal_places=12, max_digits=15)),
                ('finish', models.DecimalField(decimal_places=12, max_digits=15)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.media', verbose_name='Иконка')),
            ],
        ),
    ]
