# Generated by Django 5.0.6 on 2024-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0002_remove_kilometers_icon_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilometers',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='kilometers',
            name='start',
        ),
        migrations.AddField(
            model_name='kilometers',
            name='finish_latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='kilometers',
            name='finish_longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='kilometers',
            name='start_latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='kilometers',
            name='start_longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='kilometers',
            name='distance',
            field=models.IntegerField(verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='kilometers',
            name='name',
            field=models.IntegerField(verbose_name='Километр'),
        ),
    ]
