# Generated by Django 5.0.6 on 2024-05-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0003_remove_kilometers_finish_remove_kilometers_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilometers',
            name='finish_latitude',
        ),
        migrations.RemoveField(
            model_name='kilometers',
            name='finish_longitude',
        ),
    ]
