# Generated by Django 5.0.6 on 2024-05-30 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0004_remove_kilometers_finish_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.FileField(upload_to='', verbose_name='Медиа')),
            ],
        ),
        migrations.AlterField(
            model_name='kilometers',
            name='start_latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='kilometers',
            name='start_longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Широта'),
        ),
        migrations.CreateModel(
            name='Artificial_Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Долгота')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.media')),
            ],
        ),
    ]
