# Generated by Django 5.0.6 on 2024-06-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0006_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability_Artificial_Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наличие ИССО')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Catchment_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Площадь водосбора')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Changing_Watercours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Изменение естественного характера водотока')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Condition_Culvert_Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Состояние ИССО по водопропускной способности')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Condition_Drainage_Ditches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Состояние водоотводных канав')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Cross_Country_Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наличие притрассовых автодорог')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Dams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Водораздельные и водооградительные дамбы')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Height_Embankmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Диапозон высоты насыпи')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Strengthening_Bridge_Cones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Укрепления конусов мостов')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Sufficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Обеспеченность материалами и инструментом для водоборьбы')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Рельеф местности с уклонами')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Ballast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа балласта')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Rail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа шпал')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Flow_Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Направление потока воды')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Flow_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Скорость потока воды')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Стаж работы')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Веса')),
                ('risk', models.IntegerField(verbose_name='Риск')),
            ],
        ),
        migrations.AddField(
            model_name='kilometers',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.station'),
        ),
        migrations.CreateModel(
            name='Characteristic_Artificial_Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_artificial_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.availability_artificial_construction')),
                ('catchment_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.catchment_area')),
                ('changing_watercours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.changing_watercours')),
                ('kilometers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.kilometers')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.artificial_construction')),
                ('condition_culvert_capacity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.condition_culvert_capacity')),
                ('condition_drainage_ditches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.condition_drainage_ditches')),
                ('cross_country_roads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.cross_country_roads')),
                ('dams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.dams')),
                ('height_embankmen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.height_embankmen')),
                ('strengthening_bridge_cones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.strengthening_bridge_cones')),
                ('sufficiency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.sufficiency')),
                ('terrain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.terrain')),
                ('type_ballast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.type_ballast')),
                ('type_rail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.type_rail')),
                ('water_flow_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.water_flow_direction')),
                ('water_flow_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.water_flow_rate')),
                ('work_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.work_experience')),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата прогноза')),
                ('amount_precipitation', models.IntegerField(null=True, verbose_name='Количество осадков')),
                ('kilometers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.kilometers')),
                ('time_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.time_day')),
            ],
        ),
        migrations.CreateModel(
            name='Risk_Destroying_Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.IntegerField(null=True, verbose_name='Риск размыва пути')),
                ('characteristic_artificial_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.characteristic_artificial_construction')),
                ('weather_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.weather_report')),
            ],
        ),
    ]
