# Generated by Django 5.0.6 on 2024-07-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0007_availability_artificial_construction_catchment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilometers',
            name='start_longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Долгота'),
        ),
        migrations.CreateModel(
            name='SectionsKilometers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Широта')),
                ('start_longitude', models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Долгота')),
                ('kilometers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.kilometers')),
            ],
        ),
    ]
