# Generated by Django 5.0.6 on 2024-07-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0009_station_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilometers',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='kilometers',
            name='start_longitude',
        ),
    ]
