# Generated by Django 5.0.6 on 2024-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0010_remove_kilometers_start_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilometers',
            name='risk',
            field=models.IntegerField(null=True, verbose_name='Риск размыва'),
        ),
    ]
