# Generated by Django 5.0.6 on 2024-08-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0011_kilometers_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Artificial_Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artificial_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.artificial_construction')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive_map.media')),
            ],
        ),
    ]
